### ISSUE TITLE
Gender missing on create request and gear availability

### ISSUE THREAD

**Issue by ghost** [SEGR-SEATTLEU/FALL-2016#24]
I noticed that gender is not there tonight while I was trying to fix other issues.

**Comment by hisham02** [comment]
Fixed with pull #28

**Comment by hisham02** [comment]
Re-opening. Introduced an issue with parsing an apostrophe in JSON object

**Comment by hisham02** [comment]
Fixed, will close after Scott pushes issue #22

**Comment by hisham02** [comment]
Fixed!
